/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TailorRouteImport } from './routes/tailor'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetAppRouteImport } from './routes/get-app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TailorIndexRouteImport } from './routes/tailor/index'
import { Route as TailorSubscriptionRouteImport } from './routes/tailor/subscription'
import { Route as TailorSettingsRouteImport } from './routes/tailor/settings'
import { Route as TailorReviewsRouteImport } from './routes/tailor/reviews'
import { Route as TailorPromotionsRouteImport } from './routes/tailor/promotions'
import { Route as TailorPortfolioRouteImport } from './routes/tailor/portfolio'
import { Route as TailorMeasurementsRouteImport } from './routes/tailor/measurements'
import { Route as TailorMaterialsRouteImport } from './routes/tailor/materials'
import { Route as TailorListingsRouteImport } from './routes/tailor/listings'
import { Route as TailorInvoicesRouteImport } from './routes/tailor/invoices'
import { Route as TailorInvoicePreviewRouteImport } from './routes/tailor/invoice-preview'
import { Route as TailorEarningsRouteImport } from './routes/tailor/earnings'
import { Route as TailorDocumentsRouteImport } from './routes/tailor/documents'
import { Route as TailorDisputesRouteImport } from './routes/tailor/disputes'
import { Route as TailorAppointmentsRouteImport } from './routes/tailor/appointments'
import { Route as StoreTailorIdRouteImport } from './routes/store.$tailorId'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppVerificationRouteImport } from './routes/_app/verification'
import { Route as AppValidatorTeamsRouteImport } from './routes/_app/validator-teams'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReviewsRouteImport } from './routes/_app/reviews'
import { Route as AppRevenueRouteImport } from './routes/_app/revenue'
import { Route as AppPromotionsRouteImport } from './routes/_app/promotions'
import { Route as AppPayoutsRouteImport } from './routes/_app/payouts'
import { Route as AppOwnerRouteImport } from './routes/_app/owner'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppModerationRouteImport } from './routes/_app/moderation'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppKycReviewRouteImport } from './routes/_app/kyc-review'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppFlaggedUploadsRouteImport } from './routes/_app/flagged-uploads'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppFeeOutliersRouteImport } from './routes/_app/fee-outliers'
import { Route as AppFeaturesRouteImport } from './routes/_app/features'
import { Route as AppDeliveriesRouteImport } from './routes/_app/deliveries'
import { Route as AppContentReportsRouteImport } from './routes/_app/content-reports'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppAdminsRouteImport } from './routes/_app/admins'
import { Route as TailorOrdersIndexRouteImport } from './routes/tailor/orders.index'
import { Route as AppTailorsIndexRouteImport } from './routes/_app/tailors.index'
import { Route as AppRolesIndexRouteImport } from './routes/_app/roles.index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppDisputesIndexRouteImport } from './routes/_app/disputes.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers.index'
import { Route as TailorOrdersIdRouteImport } from './routes/tailor/orders.$id'
import { Route as AppTailorsIdRouteImport } from './routes/_app/tailors.$id'
import { Route as AppRolesMatrixRouteImport } from './routes/_app/roles.matrix'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders.$id'
import { Route as AppDisputesIdRouteImport } from './routes/_app/disputes.$id'
import { Route as AppDeliveriesControlsRouteImport } from './routes/_app/deliveries.controls'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorRoute = TailorRouteImport.update({
  id: '/tailor',
  path: '/tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAppRoute = GetAppRouteImport.update({
  id: '/get-app',
  path: '/get-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorIndexRoute = TailorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TailorRoute,
} as any)
const TailorSubscriptionRoute = TailorSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => TailorRoute,
} as any)
const TailorSettingsRoute = TailorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TailorRoute,
} as any)
const TailorReviewsRoute = TailorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => TailorRoute,
} as any)
const TailorPromotionsRoute = TailorPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => TailorRoute,
} as any)
const TailorPortfolioRoute = TailorPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => TailorRoute,
} as any)
const TailorMeasurementsRoute = TailorMeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => TailorRoute,
} as any)
const TailorMaterialsRoute = TailorMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => TailorRoute,
} as any)
const TailorListingsRoute = TailorListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => TailorRoute,
} as any)
const TailorInvoicesRoute = TailorInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => TailorRoute,
} as any)
const TailorInvoicePreviewRoute = TailorInvoicePreviewRouteImport.update({
  id: '/invoice-preview',
  path: '/invoice-preview',
  getParentRoute: () => TailorRoute,
} as any)
const TailorEarningsRoute = TailorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => TailorRoute,
} as any)
const TailorDocumentsRoute = TailorDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => TailorRoute,
} as any)
const TailorDisputesRoute = TailorDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => TailorRoute,
} as any)
const TailorAppointmentsRoute = TailorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => TailorRoute,
} as any)
const StoreTailorIdRoute = StoreTailorIdRouteImport.update({
  id: '/store/$tailorId',
  path: '/store/$tailorId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppValidatorTeamsRoute = AppValidatorTeamsRouteImport.update({
  id: '/validator-teams',
  path: '/validator-teams',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppKycReviewRoute = AppKycReviewRouteImport.update({
  id: '/kyc-review',
  path: '/kyc-review',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppFlaggedUploadsRoute = AppFlaggedUploadsRouteImport.update({
  id: '/flagged-uploads',
  path: '/flagged-uploads',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppFeeOutliersRoute = AppFeeOutliersRouteImport.update({
  id: '/fee-outliers',
  path: '/fee-outliers',
  getParentRoute: () => AppRoute,
} as any)
const AppFeaturesRoute = AppFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppContentReportsRoute = AppContentReportsRouteImport.update({
  id: '/content-reports',
  path: '/content-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminsRoute = AppAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppRoute,
} as any)
const TailorOrdersIndexRoute = TailorOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => TailorRoute,
} as any)
const AppTailorsIndexRoute = AppTailorsIndexRouteImport.update({
  id: '/tailors/',
  path: '/tailors/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesIndexRoute = AppDisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const TailorOrdersIdRoute = TailorOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => TailorRoute,
} as any)
const AppTailorsIdRoute = AppTailorsIdRouteImport.update({
  id: '/tailors/$id',
  path: '/tailors/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesMatrixRoute = AppRolesMatrixRouteImport.update({
  id: '/roles/matrix',
  path: '/roles/matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesIdRoute = AppDisputesIdRouteImport.update({
  id: '/disputes/$id',
  path: '/disputes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesControlsRoute = AppDeliveriesControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => AppDeliveriesRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-app': typeof GetAppRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/tailor': typeof TailorRouteWithChildren
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/admins': typeof AppAdminsRoute
  '/audit': typeof AppAuditRoute
  '/categories': typeof AppCategoriesRoute
  '/content-reports': typeof AppContentReportsRoute
  '/deliveries': typeof AppDeliveriesRouteWithChildren
  '/features': typeof AppFeaturesRoute
  '/fee-outliers': typeof AppFeeOutliersRoute
  '/finance': typeof AppFinanceRoute
  '/flagged-uploads': typeof AppFlaggedUploadsRoute
  '/inventory': typeof AppInventoryRoute
  '/kyc-review': typeof AppKycReviewRoute
  '/messages': typeof AppMessagesRoute
  '/moderation': typeof AppModerationRoute
  '/notifications': typeof AppNotificationsRoute
  '/overview': typeof AppOverviewRoute
  '/owner': typeof AppOwnerRoute
  '/payouts': typeof AppPayoutsRoute
  '/promotions': typeof AppPromotionsRoute
  '/revenue': typeof AppRevenueRoute
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/validator-teams': typeof AppValidatorTeamsRoute
  '/verification': typeof AppVerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listing/$id': typeof ListingIdRoute
  '/store/$tailorId': typeof StoreTailorIdRoute
  '/tailor/appointments': typeof TailorAppointmentsRoute
  '/tailor/disputes': typeof TailorDisputesRoute
  '/tailor/documents': typeof TailorDocumentsRoute
  '/tailor/earnings': typeof TailorEarningsRoute
  '/tailor/invoice-preview': typeof TailorInvoicePreviewRoute
  '/tailor/invoices': typeof TailorInvoicesRoute
  '/tailor/listings': typeof TailorListingsRoute
  '/tailor/materials': typeof TailorMaterialsRoute
  '/tailor/measurements': typeof TailorMeasurementsRoute
  '/tailor/portfolio': typeof TailorPortfolioRoute
  '/tailor/promotions': typeof TailorPromotionsRoute
  '/tailor/reviews': typeof TailorReviewsRoute
  '/tailor/settings': typeof TailorSettingsRoute
  '/tailor/subscription': typeof TailorSubscriptionRoute
  '/tailor/': typeof TailorIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/deliveries/controls': typeof AppDeliveriesControlsRoute
  '/disputes/$id': typeof AppDisputesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/roles/matrix': typeof AppRolesMatrixRoute
  '/tailors/$id': typeof AppTailorsIdRoute
  '/tailor/orders/$id': typeof TailorOrdersIdRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/disputes/': typeof AppDisputesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/roles/': typeof AppRolesIndexRoute
  '/tailors/': typeof AppTailorsIndexRoute
  '/tailor/orders/': typeof TailorOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-app': typeof GetAppRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/admins': typeof AppAdminsRoute
  '/audit': typeof AppAuditRoute
  '/categories': typeof AppCategoriesRoute
  '/content-reports': typeof AppContentReportsRoute
  '/deliveries': typeof AppDeliveriesRouteWithChildren
  '/features': typeof AppFeaturesRoute
  '/fee-outliers': typeof AppFeeOutliersRoute
  '/finance': typeof AppFinanceRoute
  '/flagged-uploads': typeof AppFlaggedUploadsRoute
  '/inventory': typeof AppInventoryRoute
  '/kyc-review': typeof AppKycReviewRoute
  '/messages': typeof AppMessagesRoute
  '/moderation': typeof AppModerationRoute
  '/notifications': typeof AppNotificationsRoute
  '/overview': typeof AppOverviewRoute
  '/owner': typeof AppOwnerRoute
  '/payouts': typeof AppPayoutsRoute
  '/promotions': typeof AppPromotionsRoute
  '/revenue': typeof AppRevenueRoute
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/validator-teams': typeof AppValidatorTeamsRoute
  '/verification': typeof AppVerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listing/$id': typeof ListingIdRoute
  '/store/$tailorId': typeof StoreTailorIdRoute
  '/tailor/appointments': typeof TailorAppointmentsRoute
  '/tailor/disputes': typeof TailorDisputesRoute
  '/tailor/documents': typeof TailorDocumentsRoute
  '/tailor/earnings': typeof TailorEarningsRoute
  '/tailor/invoice-preview': typeof TailorInvoicePreviewRoute
  '/tailor/invoices': typeof TailorInvoicesRoute
  '/tailor/listings': typeof TailorListingsRoute
  '/tailor/materials': typeof TailorMaterialsRoute
  '/tailor/measurements': typeof TailorMeasurementsRoute
  '/tailor/portfolio': typeof TailorPortfolioRoute
  '/tailor/promotions': typeof TailorPromotionsRoute
  '/tailor/reviews': typeof TailorReviewsRoute
  '/tailor/settings': typeof TailorSettingsRoute
  '/tailor/subscription': typeof TailorSubscriptionRoute
  '/tailor': typeof TailorIndexRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/deliveries/controls': typeof AppDeliveriesControlsRoute
  '/disputes/$id': typeof AppDisputesIdRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/roles/matrix': typeof AppRolesMatrixRoute
  '/tailors/$id': typeof AppTailorsIdRoute
  '/tailor/orders/$id': typeof TailorOrdersIdRoute
  '/customers': typeof AppCustomersIndexRoute
  '/disputes': typeof AppDisputesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/tailors': typeof AppTailorsIndexRoute
  '/tailor/orders': typeof TailorOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/get-app': typeof GetAppRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/tailor': typeof TailorRouteWithChildren
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/_app/admins': typeof AppAdminsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/content-reports': typeof AppContentReportsRoute
  '/_app/deliveries': typeof AppDeliveriesRouteWithChildren
  '/_app/features': typeof AppFeaturesRoute
  '/_app/fee-outliers': typeof AppFeeOutliersRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/flagged-uploads': typeof AppFlaggedUploadsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/kyc-review': typeof AppKycReviewRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/moderation': typeof AppModerationRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/owner': typeof AppOwnerRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/revenue': typeof AppRevenueRoute
  '/_app/reviews': typeof AppReviewsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/validator-teams': typeof AppValidatorTeamsRoute
  '/_app/verification': typeof AppVerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listing/$id': typeof ListingIdRoute
  '/store/$tailorId': typeof StoreTailorIdRoute
  '/tailor/appointments': typeof TailorAppointmentsRoute
  '/tailor/disputes': typeof TailorDisputesRoute
  '/tailor/documents': typeof TailorDocumentsRoute
  '/tailor/earnings': typeof TailorEarningsRoute
  '/tailor/invoice-preview': typeof TailorInvoicePreviewRoute
  '/tailor/invoices': typeof TailorInvoicesRoute
  '/tailor/listings': typeof TailorListingsRoute
  '/tailor/materials': typeof TailorMaterialsRoute
  '/tailor/measurements': typeof TailorMeasurementsRoute
  '/tailor/portfolio': typeof TailorPortfolioRoute
  '/tailor/promotions': typeof TailorPromotionsRoute
  '/tailor/reviews': typeof TailorReviewsRoute
  '/tailor/settings': typeof TailorSettingsRoute
  '/tailor/subscription': typeof TailorSubscriptionRoute
  '/tailor/': typeof TailorIndexRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/deliveries/controls': typeof AppDeliveriesControlsRoute
  '/_app/disputes/$id': typeof AppDisputesIdRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/roles/matrix': typeof AppRolesMatrixRoute
  '/_app/tailors/$id': typeof AppTailorsIdRoute
  '/tailor/orders/$id': typeof TailorOrdersIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/disputes/': typeof AppDisputesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/tailors/': typeof AppTailorsIndexRoute
  '/tailor/orders/': typeof TailorOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/get-app'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/tailor'
    | '/terms'
    | '/verify'
    | '/admins'
    | '/audit'
    | '/categories'
    | '/content-reports'
    | '/deliveries'
    | '/features'
    | '/fee-outliers'
    | '/finance'
    | '/flagged-uploads'
    | '/inventory'
    | '/kyc-review'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/overview'
    | '/owner'
    | '/payouts'
    | '/promotions'
    | '/revenue'
    | '/reviews'
    | '/settings'
    | '/validator-teams'
    | '/verification'
    | '/auth/callback'
    | '/listing/$id'
    | '/store/$tailorId'
    | '/tailor/appointments'
    | '/tailor/disputes'
    | '/tailor/documents'
    | '/tailor/earnings'
    | '/tailor/invoice-preview'
    | '/tailor/invoices'
    | '/tailor/listings'
    | '/tailor/materials'
    | '/tailor/measurements'
    | '/tailor/portfolio'
    | '/tailor/promotions'
    | '/tailor/reviews'
    | '/tailor/settings'
    | '/tailor/subscription'
    | '/tailor/'
    | '/customers/$id'
    | '/deliveries/controls'
    | '/disputes/$id'
    | '/orders/$id'
    | '/roles/matrix'
    | '/tailors/$id'
    | '/tailor/orders/$id'
    | '/customers/'
    | '/disputes/'
    | '/orders/'
    | '/roles/'
    | '/tailors/'
    | '/tailor/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/get-app'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/verify'
    | '/admins'
    | '/audit'
    | '/categories'
    | '/content-reports'
    | '/deliveries'
    | '/features'
    | '/fee-outliers'
    | '/finance'
    | '/flagged-uploads'
    | '/inventory'
    | '/kyc-review'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/overview'
    | '/owner'
    | '/payouts'
    | '/promotions'
    | '/revenue'
    | '/reviews'
    | '/settings'
    | '/validator-teams'
    | '/verification'
    | '/auth/callback'
    | '/listing/$id'
    | '/store/$tailorId'
    | '/tailor/appointments'
    | '/tailor/disputes'
    | '/tailor/documents'
    | '/tailor/earnings'
    | '/tailor/invoice-preview'
    | '/tailor/invoices'
    | '/tailor/listings'
    | '/tailor/materials'
    | '/tailor/measurements'
    | '/tailor/portfolio'
    | '/tailor/promotions'
    | '/tailor/reviews'
    | '/tailor/settings'
    | '/tailor/subscription'
    | '/tailor'
    | '/customers/$id'
    | '/deliveries/controls'
    | '/disputes/$id'
    | '/orders/$id'
    | '/roles/matrix'
    | '/tailors/$id'
    | '/tailor/orders/$id'
    | '/customers'
    | '/disputes'
    | '/orders'
    | '/roles'
    | '/tailors'
    | '/tailor/orders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/contact'
    | '/get-app'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/tailor'
    | '/terms'
    | '/verify'
    | '/_app/admins'
    | '/_app/audit'
    | '/_app/categories'
    | '/_app/content-reports'
    | '/_app/deliveries'
    | '/_app/features'
    | '/_app/fee-outliers'
    | '/_app/finance'
    | '/_app/flagged-uploads'
    | '/_app/inventory'
    | '/_app/kyc-review'
    | '/_app/messages'
    | '/_app/moderation'
    | '/_app/notifications'
    | '/_app/overview'
    | '/_app/owner'
    | '/_app/payouts'
    | '/_app/promotions'
    | '/_app/revenue'
    | '/_app/reviews'
    | '/_app/settings'
    | '/_app/validator-teams'
    | '/_app/verification'
    | '/auth/callback'
    | '/listing/$id'
    | '/store/$tailorId'
    | '/tailor/appointments'
    | '/tailor/disputes'
    | '/tailor/documents'
    | '/tailor/earnings'
    | '/tailor/invoice-preview'
    | '/tailor/invoices'
    | '/tailor/listings'
    | '/tailor/materials'
    | '/tailor/measurements'
    | '/tailor/portfolio'
    | '/tailor/promotions'
    | '/tailor/reviews'
    | '/tailor/settings'
    | '/tailor/subscription'
    | '/tailor/'
    | '/_app/customers/$id'
    | '/_app/deliveries/controls'
    | '/_app/disputes/$id'
    | '/_app/orders/$id'
    | '/_app/roles/matrix'
    | '/_app/tailors/$id'
    | '/tailor/orders/$id'
    | '/_app/customers/'
    | '/_app/disputes/'
    | '/_app/orders/'
    | '/_app/roles/'
    | '/_app/tailors/'
    | '/tailor/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GetAppRoute: typeof GetAppRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TailorRoute: typeof TailorRouteWithChildren
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ListingIdRoute: typeof ListingIdRoute
  StoreTailorIdRoute: typeof StoreTailorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor': {
      id: '/tailor'
      path: '/tailor'
      fullPath: '/tailor'
      preLoaderRoute: typeof TailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-app': {
      id: '/get-app'
      path: '/get-app'
      fullPath: '/get-app'
      preLoaderRoute: typeof GetAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor/': {
      id: '/tailor/'
      path: '/'
      fullPath: '/tailor/'
      preLoaderRoute: typeof TailorIndexRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/subscription': {
      id: '/tailor/subscription'
      path: '/subscription'
      fullPath: '/tailor/subscription'
      preLoaderRoute: typeof TailorSubscriptionRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/settings': {
      id: '/tailor/settings'
      path: '/settings'
      fullPath: '/tailor/settings'
      preLoaderRoute: typeof TailorSettingsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/reviews': {
      id: '/tailor/reviews'
      path: '/reviews'
      fullPath: '/tailor/reviews'
      preLoaderRoute: typeof TailorReviewsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/promotions': {
      id: '/tailor/promotions'
      path: '/promotions'
      fullPath: '/tailor/promotions'
      preLoaderRoute: typeof TailorPromotionsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/portfolio': {
      id: '/tailor/portfolio'
      path: '/portfolio'
      fullPath: '/tailor/portfolio'
      preLoaderRoute: typeof TailorPortfolioRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/measurements': {
      id: '/tailor/measurements'
      path: '/measurements'
      fullPath: '/tailor/measurements'
      preLoaderRoute: typeof TailorMeasurementsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/materials': {
      id: '/tailor/materials'
      path: '/materials'
      fullPath: '/tailor/materials'
      preLoaderRoute: typeof TailorMaterialsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/listings': {
      id: '/tailor/listings'
      path: '/listings'
      fullPath: '/tailor/listings'
      preLoaderRoute: typeof TailorListingsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/invoices': {
      id: '/tailor/invoices'
      path: '/invoices'
      fullPath: '/tailor/invoices'
      preLoaderRoute: typeof TailorInvoicesRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/invoice-preview': {
      id: '/tailor/invoice-preview'
      path: '/invoice-preview'
      fullPath: '/tailor/invoice-preview'
      preLoaderRoute: typeof TailorInvoicePreviewRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/earnings': {
      id: '/tailor/earnings'
      path: '/earnings'
      fullPath: '/tailor/earnings'
      preLoaderRoute: typeof TailorEarningsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/documents': {
      id: '/tailor/documents'
      path: '/documents'
      fullPath: '/tailor/documents'
      preLoaderRoute: typeof TailorDocumentsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/disputes': {
      id: '/tailor/disputes'
      path: '/disputes'
      fullPath: '/tailor/disputes'
      preLoaderRoute: typeof TailorDisputesRouteImport
      parentRoute: typeof TailorRoute
    }
    '/tailor/appointments': {
      id: '/tailor/appointments'
      path: '/appointments'
      fullPath: '/tailor/appointments'
      preLoaderRoute: typeof TailorAppointmentsRouteImport
      parentRoute: typeof TailorRoute
    }
    '/store/$tailorId': {
      id: '/store/$tailorId'
      path: '/store/$tailorId'
      fullPath: '/store/$tailorId'
      preLoaderRoute: typeof StoreTailorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verification': {
      id: '/_app/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/validator-teams': {
      id: '/_app/validator-teams'
      path: '/validator-teams'
      fullPath: '/validator-teams'
      preLoaderRoute: typeof AppValidatorTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revenue': {
      id: '/_app/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner': {
      id: '/_app/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kyc-review': {
      id: '/_app/kyc-review'
      path: '/kyc-review'
      fullPath: '/kyc-review'
      preLoaderRoute: typeof AppKycReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flagged-uploads': {
      id: '/_app/flagged-uploads'
      path: '/flagged-uploads'
      fullPath: '/flagged-uploads'
      preLoaderRoute: typeof AppFlaggedUploadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fee-outliers': {
      id: '/_app/fee-outliers'
      path: '/fee-outliers'
      fullPath: '/fee-outliers'
      preLoaderRoute: typeof AppFeeOutliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/features': {
      id: '/_app/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AppFeaturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries': {
      id: '/_app/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content-reports': {
      id: '/_app/content-reports'
      path: '/content-reports'
      fullPath: '/content-reports'
      preLoaderRoute: typeof AppContentReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admins': {
      id: '/_app/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AppAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    '/tailor/orders/': {
      id: '/tailor/orders/'
      path: '/orders'
      fullPath: '/tailor/orders/'
      preLoaderRoute: typeof TailorOrdersIndexRouteImport
      parentRoute: typeof TailorRoute
    }
    '/_app/tailors/': {
      id: '/_app/tailors/'
      path: '/tailors'
      fullPath: '/tailors/'
      preLoaderRoute: typeof AppTailorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disputes/': {
      id: '/_app/disputes/'
      path: '/disputes'
      fullPath: '/disputes/'
      preLoaderRoute: typeof AppDisputesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/tailor/orders/$id': {
      id: '/tailor/orders/$id'
      path: '/orders/$id'
      fullPath: '/tailor/orders/$id'
      preLoaderRoute: typeof TailorOrdersIdRouteImport
      parentRoute: typeof TailorRoute
    }
    '/_app/tailors/$id': {
      id: '/_app/tailors/$id'
      path: '/tailors/$id'
      fullPath: '/tailors/$id'
      preLoaderRoute: typeof AppTailorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/matrix': {
      id: '/_app/roles/matrix'
      path: '/roles/matrix'
      fullPath: '/roles/matrix'
      preLoaderRoute: typeof AppRolesMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disputes/$id': {
      id: '/_app/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof AppDisputesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries/controls': {
      id: '/_app/deliveries/controls'
      path: '/controls'
      fullPath: '/deliveries/controls'
      preLoaderRoute: typeof AppDeliveriesControlsRouteImport
      parentRoute: typeof AppDeliveriesRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppDeliveriesRouteChildren {
  AppDeliveriesControlsRoute: typeof AppDeliveriesControlsRoute
}

const AppDeliveriesRouteChildren: AppDeliveriesRouteChildren = {
  AppDeliveriesControlsRoute: AppDeliveriesControlsRoute,
}

const AppDeliveriesRouteWithChildren = AppDeliveriesRoute._addFileChildren(
  AppDeliveriesRouteChildren,
)

interface AppRouteChildren {
  AppAdminsRoute: typeof AppAdminsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppContentReportsRoute: typeof AppContentReportsRoute
  AppDeliveriesRoute: typeof AppDeliveriesRouteWithChildren
  AppFeaturesRoute: typeof AppFeaturesRoute
  AppFeeOutliersRoute: typeof AppFeeOutliersRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFlaggedUploadsRoute: typeof AppFlaggedUploadsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppKycReviewRoute: typeof AppKycReviewRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppModerationRoute: typeof AppModerationRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppOwnerRoute: typeof AppOwnerRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppValidatorTeamsRoute: typeof AppValidatorTeamsRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppDisputesIdRoute: typeof AppDisputesIdRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppRolesMatrixRoute: typeof AppRolesMatrixRoute
  AppTailorsIdRoute: typeof AppTailorsIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDisputesIndexRoute: typeof AppDisputesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppTailorsIndexRoute: typeof AppTailorsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminsRoute: AppAdminsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppContentReportsRoute: AppContentReportsRoute,
  AppDeliveriesRoute: AppDeliveriesRouteWithChildren,
  AppFeaturesRoute: AppFeaturesRoute,
  AppFeeOutliersRoute: AppFeeOutliersRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFlaggedUploadsRoute: AppFlaggedUploadsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppKycReviewRoute: AppKycReviewRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppModerationRoute: AppModerationRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppOwnerRoute: AppOwnerRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppValidatorTeamsRoute: AppValidatorTeamsRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppDisputesIdRoute: AppDisputesIdRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppRolesMatrixRoute: AppRolesMatrixRoute,
  AppTailorsIdRoute: AppTailorsIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDisputesIndexRoute: AppDisputesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppTailorsIndexRoute: AppTailorsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TailorRouteChildren {
  TailorAppointmentsRoute: typeof TailorAppointmentsRoute
  TailorDisputesRoute: typeof TailorDisputesRoute
  TailorDocumentsRoute: typeof TailorDocumentsRoute
  TailorEarningsRoute: typeof TailorEarningsRoute
  TailorInvoicePreviewRoute: typeof TailorInvoicePreviewRoute
  TailorInvoicesRoute: typeof TailorInvoicesRoute
  TailorListingsRoute: typeof TailorListingsRoute
  TailorMaterialsRoute: typeof TailorMaterialsRoute
  TailorMeasurementsRoute: typeof TailorMeasurementsRoute
  TailorPortfolioRoute: typeof TailorPortfolioRoute
  TailorPromotionsRoute: typeof TailorPromotionsRoute
  TailorReviewsRoute: typeof TailorReviewsRoute
  TailorSettingsRoute: typeof TailorSettingsRoute
  TailorSubscriptionRoute: typeof TailorSubscriptionRoute
  TailorIndexRoute: typeof TailorIndexRoute
  TailorOrdersIdRoute: typeof TailorOrdersIdRoute
  TailorOrdersIndexRoute: typeof TailorOrdersIndexRoute
}

const TailorRouteChildren: TailorRouteChildren = {
  TailorAppointmentsRoute: TailorAppointmentsRoute,
  TailorDisputesRoute: TailorDisputesRoute,
  TailorDocumentsRoute: TailorDocumentsRoute,
  TailorEarningsRoute: TailorEarningsRoute,
  TailorInvoicePreviewRoute: TailorInvoicePreviewRoute,
  TailorInvoicesRoute: TailorInvoicesRoute,
  TailorListingsRoute: TailorListingsRoute,
  TailorMaterialsRoute: TailorMaterialsRoute,
  TailorMeasurementsRoute: TailorMeasurementsRoute,
  TailorPortfolioRoute: TailorPortfolioRoute,
  TailorPromotionsRoute: TailorPromotionsRoute,
  TailorReviewsRoute: TailorReviewsRoute,
  TailorSettingsRoute: TailorSettingsRoute,
  TailorSubscriptionRoute: TailorSubscriptionRoute,
  TailorIndexRoute: TailorIndexRoute,
  TailorOrdersIdRoute: TailorOrdersIdRoute,
  TailorOrdersIndexRoute: TailorOrdersIndexRoute,
}

const TailorRouteWithChildren =
  TailorRoute._addFileChildren(TailorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GetAppRoute: GetAppRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TailorRoute: TailorRouteWithChildren,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ListingIdRoute: ListingIdRoute,
  StoreTailorIdRoute: StoreTailorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
